import jsPDF from "jspdf";
import type { BrandBlueprint } from "@/lib/brandBlueprint";

const MARGIN = 40;
const FOOTER_TEXT = "Generated by VVCLab";

function slug(s: string) {
  return (
    s
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "blueprint"
  );
}

function buildPlainText(bp: BrandBlueprint, userName: string) {
  const lines: string[] = [];
  lines.push(`${userName} — Brand Blueprint`);
  lines.push("");
  lines.push(`YouTube Niche: ${bp.youtubeNiche}`);
  lines.push("");
  lines.push("Brand Summary");
  lines.push(bp.brandSummary);
  lines.push("");
  lines.push("Content Pillars");
  bp.contentPillars.forEach((p, i) => lines.push(`${i + 1}. ${p}`));
  lines.push("");
  lines.push("Brand Voice");
  lines.push(bp.brandVoice);
  lines.push("");
  lines.push("Target Audience");
  lines.push(bp.targetAudience);
  lines.push("");
  lines.push("Monetisation Angle");
  lines.push(bp.monetisationAngle);
  return lines.join("\n");
}

export function buildBlueprintEmail(bp: BrandBlueprint, userName: string) {
  const subject = `${bp.name} — Brand Blueprint`;
  const body = buildPlainText(bp, userName);
  return { subject, body };
}

export function generateBlueprintPdf(bp: BrandBlueprint, userName: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - MARGIN * 2;
  let y = MARGIN;

  const addFooter = () => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(140);
    doc.text(FOOTER_TEXT, pageWidth / 2, pageHeight - 20, { align: "center" });
    doc.setTextColor(0);
  };

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - MARGIN - 20) {
      addFooter();
      doc.addPage();
      y = MARGIN;
    }
  };

  const writeHeading = (text: string) => {
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(text, MARGIN, y);
    y += 18;
  };

  const writeBody = (text: string, size = 11) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text || "—", contentWidth) as string[];
    const lineHeight = size * 1.35;
    for (const line of lines) {
      ensureSpace(lineHeight);
      doc.text(line, MARGIN, y);
      y += lineHeight;
    }
  };

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("VVCLab", MARGIN, y);
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text(dateStr, pageWidth - MARGIN, y, { align: "right" });
  doc.setTextColor(0);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(userName, MARGIN, y);
  y += 24;
  doc.setDrawColor(220);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 18;

  // Section 1: Niche + Brand Summary
  writeHeading("YouTube Niche");
  writeBody(bp.youtubeNiche);
  y += 6;
  writeHeading("Brand Summary");
  writeBody(bp.brandSummary);
  y += 6;

  // Section 2: Content Pillars
  writeHeading("Content Pillars");
  bp.contentPillars.forEach((p, i) => writeBody(`${i + 1}. ${p}`));
  y += 6;

  // Section 3: Brand Voice
  writeHeading("Brand Voice");
  writeBody(bp.brandVoice);
  y += 6;

  // Section 4: Target Audience
  writeHeading("Target Audience");
  writeBody(bp.targetAudience);
  y += 6;

  // Section 5: Monetisation Angle
  writeHeading("Monetisation Angle");
  writeBody(bp.monetisationAngle);

  addFooter();

  const filename = `${slug(bp.name)}-brand-blueprint.pdf`;
  doc.save(filename);
}
