import { createFileRoute } from "@tanstack/react-router";
import { MarketingLayout } from "@/components/marketing/MarketingLayout";


export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — VVCLab" },
      { name: "description", content: "The terms that govern your use of VVCLab." },
      { property: "og:title", content: "Terms of Service — VVCLab" },
      { property: "og:description", content: "The terms that govern your use of VVCLab." },
    ],
  }),
  component: TermsPage,
});

type Section = { heading: string; body: React.ReactNode };

const SECTIONS: Section[] = [
  {
    heading: "Acceptance",
    body: `By creating a VVCLab account, you agree to these terms. If you do not agree, do not use VVCLab.`,
  },
  {
    heading: "What VVCLab provides",
    body: `VVCLab is a YouTube competitor intelligence tool. We fetch publicly available YouTube data, analyse it, and generate script suggestions using AI. All generated scripts are suggestions — you are responsible for reviewing, editing, and taking ownership of any content you publish.`,
  },
  {
    heading: "Your account",
    body: `You are responsible for keeping your account credentials secure. You must be 16 or older to use VVCLab. One account per person.`,
  },
  {
    heading: "Acceptable use",
    body: `You may not use VVCLab to generate content that is illegal, defamatory, or infringes third-party intellectual property. You may not scrape or reverse-engineer VVCLab. You may not use VVCLab to spam or harass others.`,
  },
  {
    heading: "AI-generated content",
    body: `Scripts and posts generated by VVCLab are AI-generated suggestions. We do not guarantee their accuracy, originality, or fitness for any purpose. You own the content you generate and are responsible for what you publish.`,
  },
  {
    heading: "YouTube API",
    body: (
      <>
        VVCLab uses the YouTube Data API v3 and complies with YouTube's Terms of Service. By using
        VVCLab, you also agree to{" "}
        <a
          href="https://www.youtube.com/t/terms"
          target="_blank"
          rel="noreferrer"
          className="underline hover:opacity-80"
          style={{ color: "var(--m-gold)" }}
        >
          YouTube's Terms of Service
        </a>

        .
      </>
    ),
  },
  {
    heading: "Payment and refunds",
    body: `Pro plan payments are processed by Stripe. The 7-day free trial can be cancelled at any time before the trial ends for no charge. We do not offer refunds for partial billing periods.`,
  },
  {
    heading: "Termination",
    body: `We reserve the right to suspend or delete accounts that violate these terms. You may delete your account at any time from Settings.`,
  },
  {
    heading: "Limitation of liability",
    body: `VVCLab is provided "as is." We are not liable for any indirect, incidental, or consequential damages arising from your use of VVCLab.`,
  },
  {
    heading: "Governing law",
    body: `These terms are governed by the laws of Nigeria.`,
  },
  {
    heading: "Contact",
    body: `For any questions about these terms, email mrolayokun@gmail.com`,
  },
];

function TermsPage() {
  return (
    <MarketingLayout>
      <section className="px-8 py-24">
        <div className="mx-auto max-w-[720px]">
          <h1 className="mt-6 text-[48px] font-bold leading-tight text-white">Terms of Service</h1>
          <p className="mt-3 text-[15px]" style={{ color: "var(--m-text-secondary)" }}>
            Last updated: May 30, 2026
          </p>
          <div
            className="mt-12 space-y-10 text-[15px] leading-relaxed"
            style={{ color: "var(--m-text-secondary)" }}
          >
            {SECTIONS.map((s) => (
              <div key={s.heading}>
                <h2 className="mb-3 text-xl font-bold text-white">{s.heading}</h2>
                <p>{s.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}
