// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Skip during SSR — no browser session is available, and protected
    // server fns gate themselves; let the route's auth guard handle it.
    if (typeof window === 'undefined') {
      return next()
    }
    const { supabase } = await import('./client')
    // getUser() awaits the async session restore from localStorage so the
    // access token is present on the very first call after a hard reload.
    await supabase.auth.getUser()
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    if (!token) {
      return next()
    }
    return next({
      headers: { Authorization: `Bearer ${token}` },
    })
  },
)
