// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kihjvepfhezwqwgziutt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpaGp2ZXBmaGV6d3F3Z3ppdXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAwNjc2ODAsImV4cCI6MjA5NTY0MzY4MH0.ePpG3wd3q7QgvLfdqO8saWyqUtd_LtmJfPJvU2E0Zv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});